package com.makeuseof.core.network

enum class NetworkError {
	UNAUTHORIZED,
	CONTENT_NOT_FOUND,
	CONNECTION_ERROR,
	ACTION_ERROR,
	NULL_RESPONSE,
	SERVER_MAINTENANCE,
	EMPTY_BODY,
	SERVER_ERROR,
	UNHANDLED_ERROR,
	INCORRECT_INPUT,
	FORBIDDEN
}